version: "3.8"
services:
  selenium-hub:
    image: selenium/hub
    ports:
      - "4545:4444"
    environment: 
      GRID_MAX_SESSION: 16
      GRID_BROWSER_TIMEOUT: 300
      GRID_TIMEOUT: 300
  chrome:
    image: selenium/node-chrome
    depends_on:
      - selenium-hub
    environment: 
     - HUB_HOST=selenium-hub
     - HUB_PORT=4444
     - NODE_MAX_SESSION=3
     - NODE_MAX_INSTANCES=8
    ports:
      - "5900:5900"
    volumes:
      - /dev/shm:/dev/shm
    links:
      - selenium-hub
      
  firefox:
    image: selenium/node-firefox
    depends_on:
      - selenium-hub
    environment: 
     - HUB_HOST=selenium-hub
     - HUB_PORT=4444
     - NODE_MAX_SESSION=3
     - NODE_MAX_INSTANCES=5
    ports:
      - "5901:5901"
    volumes:
      - /dev/shm:/dev/shm
    links:
      - selenium-hub
    